import type { Metadata } from "next";
import localFont from "next/font/local";

import { ThemeProvider } from "@/features/theming";
import StoreProvider from "@/store/StoreProvider";

import "../styles/global.scss";

const openSans = localFont({
  src: [
    {
      path: "../public/fonts/OpenSans-Regular.woff2",
      weight: "100 400",
      style: "normal",
    },
    {
      path: "../public/fonts/OpenSans-Bold.woff2",
      weight: "500 900",
      style: "normal",
    },
  ],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <StoreProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
